volumes:
  prometheus_data: {}
  gohome: {}
  awscli: {}

networks:
  promapi:

services:
  prometheus:
    image: prom/prometheus:v2.54.1
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    networks:
      - promapi
    restart: always

  rds_enhanced_monitoring_exporter:
    build:
      context: ./rds_enhanced_monitoring_exporter
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace:cached
      - gohome:/home/vscode/go:cached
      - ~/.aws/credentials:/home/vscode/.aws/credentials:ro
      - ~/.aws/config:/home/vscode/.aws/config:ro
      - awscli:/home/vscode/.aws/cli:cached
    networks:
      - promapi
    user: vscode
    depends_on:
      - prometheus
