global:
  scrape_interval: 15s

scrape_configs:
  - job_name: rds_enhanced_monitoring
    honor_labels: true
    file_sd_configs:
      - files:
          - /etc/prometheus/rds.json
        refresh_interval: 15s
    relabel_configs:
      - source_labels:
          - __meta_rds_resource_id
        target_label: __param_ResourceId
      - target_label: __address__
        replacement: rds_enhanced_monitoring_exporter:9408
